//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace makeBreak.Src.Features.Shell.Resources
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShellStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ShellStrings()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("makeBreak.Src.Features.Shell.Resources.ShellStrings", typeof(ShellStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string MainWindowTitle
        {
            get { return ResourceManager.GetString("MainWindowTitle", resourceCulture); }
        }

        public static string TraySettings
        {
            get { return ResourceManager.GetString("TraySettings", resourceCulture); }
        }

        public static string TrayShowProgress
        {
            get { return ResourceManager.GetString("TrayShowProgress", resourceCulture); }
        }

        public static string TrayStop
        {
            get { return ResourceManager.GetString("TrayStop", resourceCulture); }
        }

        public static string TrayResume
        {
            get { return ResourceManager.GetString("TrayResume", resourceCulture); }
        }

        public static string TrayExit
        {
            get { return ResourceManager.GetString("TrayExit", resourceCulture); }
        }
    }
}