//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace makeBreak.Src.Features.Statistics.Resources
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatisticsStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatisticsStrings()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("makeBreak.Src.Features.Statistics.Resources.StatisticsStrings", typeof(StatisticsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string WindowTitle
        {
            get { return ResourceManager.GetString("WindowTitle", resourceCulture); }
        }

        public static string LastDaysLabel
        {
            get { return ResourceManager.GetString("LastDaysLabel", resourceCulture); }
        }

        public static string LastMonthsLabel
        {
            get { return ResourceManager.GetString("LastMonthsLabel", resourceCulture); }
        }

        public static string WeekPeriodLabel
        {
            get { return ResourceManager.GetString("WeekPeriodLabel", resourceCulture); }
        }

        public static string MonthPeriodLabel
        {
            get { return ResourceManager.GetString("MonthPeriodLabel", resourceCulture); }
        }

        public static string YearPeriodLabel
        {
            get { return ResourceManager.GetString("YearPeriodLabel", resourceCulture); }
        }

        public static string TotalTimeFormat
        {
            get { return ResourceManager.GetString("TotalTimeFormat", resourceCulture); }
        }
    }
}